### ISSUE TITLE
Does this code work for 2d? 

### ISSUE THREAD

**Issue by chuan137** [danstowell/gmphd#1]
The example seems to be 1d.

**Comment by danstowell** [comment]
Yes, should do.

**Comment by chuan137** [comment]
Here is a snippet of my code for 2d object tracking

``` python
birthgmm = [ GmphdComponent(1,  np.array([100,100,0,0]).T, initcovar) ]                                                                                                                                                                   
g = Gmphd(birthgmm, survprob, detecprob, F, Q, H, R, clutterrate)                                                                                                                                                                         

obs = np.array([102, 108]).T                                                                                                                                                                                                              
g.update([ obs ])
```

somehow, it fails at the update step

**Comment by danstowell** [comment]
`[100,100,0,0]` is not 2D, it's 4D

**Comment by chuan137** [comment]
Extra 0 meant to be momentum in the state vector. You are indicating they are redundant here?

**Comment by danstowell** [comment]
Either the state vector is 2D, or the state vector is 4D. Your choice, but you have to be consistent

**Comment by danstowell** [comment]
Actually wait, I wasn't quite right. The state vector can be different from the observation vector. It depends on the shapes of the matrices that relate them to each other. The easiest way to clarify is if you supply a self-contained complete code example that exhibits the potential problem

**Comment by danstowell** [comment]
See for example `obsnmatrix` in `syntheticexamplestuff.py` - it shows two exmaples: 1D-obs-for-3D-state, and 2D-obs-for-3D-state

**Comment by chuan137** [comment]
Thanks, I will look at your example.

**Comment by chuan137** [comment]
Turns out I need to make sure the observations are column vectors. It works very well. Thanks for sharing the code.

Besides, I have read your two blog posts about using the filter. You mentioned the 'cold start' problem. Do you have more insights since you wrote the post?

**Comment by danstowell** [comment]
Great! I'm glad you got it working.

I must confess that I have not used GMPHD much since I originally did this work ([summarised in this brief 2012 paper](http://c4dm.eecs.qmul.ac.uk/papers/2012/StowellPlumbley2012mml.pdf)). I don't have much to say about the "cold start" problem, except that it would probably help to use a "forward-backward" approach rather than just a "filter" approach.
