### ISSUE TITLE
Data association

### ISSUE THREAD

**Issue by nwesem** [danstowell/gmphd#2]
Hi @danstowell,
first of all thank you for making this project open-source I have been testing different implementations of GM-PHD filters. Yours also looks very promising. I was wondering if you took care of the data association problem in this implementation. Do you keep track of target IDs in some way? I would appreciate your help.
Cheers nwesem

**Comment by danstowell** [comment]
Hi, and thanks. No, there is no data association in this implementation.

I'm not actively working in this area at the moment. I would consider pull requests, but I won't be coding much in this codebase.
